
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%=ENV.fetch('POSTGRES_DB') %>
  host: <%=ENV.fetch('DB_URL') %>
  username: <%=ENV.fetch("PGUSER") %>
  password: <%=ENV.fetch('PGPASSWORD') %>
  port: <%=ENV.fetch('PG_PORT') %>

test:
  <<: *default
  database: ftp_mvc_test


production:
  <<: *default
  database: <%=ENV.fetch('POSTGRES_DB') %>
  host: <%=ENV.fetch('DB_URL') %>
  username: <%=ENV.fetch("PGUSER") %>
  password: <%=ENV.fetch('PGPASSWORD') %>
